//! Distributed Key Generation (DKG) for Threshold ML-DSA.
//!
//! Implements ePrint 2026/013 §4.3: a 2-round commitment-based DKG protocol
//! that allows N parties to collaboratively generate a threshold keypair
//! without relying on a single trusted dealer.
//!
//! ## Protocol Flow
//!
//! 1. **Round 1 (Commitment):** Each party `i` samples a fresh 32-byte secret contribution `c_i`
//!    and computes commitment `h_i = H("th-ml-dsa-dkg-commit-v1" ‖ i ‖ c_i)`. Parties broadcast `h_i`.
//! 2. **Round 2 (Reveal & Verify):** Each party reveals `c_i`. All parties verify every commitment
//!    `h_j == H("th-ml-dsa-dkg-commit-v1" ‖ j ‖ c_j)`.
//! 3. **Combine & Keygen:** The master seed is derived as `S = H("th-ml-dsa-dkg-seed-v1" ‖ c_0 ‖ ... ‖ c_{N-1})`.
//!    All parties deterministically run `keygen_from_seed(S, params)` to obtain their private key shares
//!    and the public key.

#[cfg(not(feature = "std"))]
use alloc::vec::Vec;
#[cfg(feature = "std")]
use std::vec::Vec;

use crate::error::Error;
use crate::params::{ThresholdParams, MAX_PARTIES, PK_BYTES};
use crate::rss::{keygen_from_seed, ThresholdPrivateKey};
use rand_core::{CryptoRng, RngCore};
use sha3::digest::{ExtendableOutput, Update, XofReader};
use sha3::Shake256;
use subtle::ConstantTimeEq;
use zeroize::Zeroize;

/// Secret contribution generated by a party in DKG Round 1.
#[derive(Clone, Zeroize)]
#[zeroize(drop)]
pub struct DkgContribution {
    pub(crate) party_id: u8,
    pub(crate) seed: [u8; 32],
}

impl DkgContribution {
    /// Create a DkgContribution from party ID and raw seed bytes.
    #[must_use]
    pub fn from_raw(party_id: u8, seed: [u8; 32]) -> Self {
        Self { party_id, seed }
    }

    /// Party ID associated with this contribution.
    #[must_use]
    pub fn party_id(&self) -> u8 {
        self.party_id
    }

    /// Contribution seed bytes.
    #[must_use]
    pub fn seed(&self) -> &[u8; 32] {
        &self.seed
    }
}

/// DKG Round 1: Generate a secret contribution seed and its commitment hash.
///
/// # Arguments
/// * `party_id` — ID of this party (0 <= party_id < N)
/// * `rng` — CSPRNG
///
/// # Returns
/// `Ok((contribution, commitment_hash))` — Party keeps `contribution` secret until Round 2
/// and broadcasts `commitment_hash`.
pub fn dkg_round1<R: RngCore + CryptoRng>(
    party_id: u8,
    rng: &mut R,
) -> Result<(DkgContribution, [u8; 32]), Error> {
    if party_id as usize >= MAX_PARTIES {
        return Err(Error::InvalidParameters);
    }

    let mut seed = [0u8; 32];
    rng.fill_bytes(&mut seed);

    let commitment = compute_dkg_commitment(party_id, &seed);

    let contrib = DkgContribution { party_id, seed };
    Ok((contrib, commitment))
}

/// Compute commitment hash for a contribution seed.
fn compute_dkg_commitment(party_id: u8, seed: &[u8; 32]) -> [u8; 32] {
    let mut h = Shake256::default();
    h.update(b"th-ml-dsa-dkg-commit-v1");
    h.update(&[party_id]);
    h.update(seed);
    let mut out = [0u8; 32];
    h.finalize_xof().read(&mut out);
    out
}

/// DKG Round 2: Verify all party commitments and derive the combined master seed.
///
/// # Arguments
/// * `n` — Total number of parties N
/// * `contributions` — List of `(party_id, contribution)` from all N parties
/// * `commitments` — List of `(party_id, commitment)` from all N parties
///
/// # Returns
/// `Ok(combined_master_seed)` — 32-byte seed for deterministic threshold keygen.
///
/// # Errors
/// Returns `Error::InvalidShare` if any commitment fails verification or party IDs are invalid.
pub fn dkg_round2(
    n: u8,
    contributions: &[(u8, DkgContribution)],
    commitments: &[(u8, [u8; 32])],
) -> Result<[u8; 32], Error> {
    if n < 2 || (n as usize) > MAX_PARTIES || contributions.len() != n as usize || commitments.len() != n as usize {
        return Err(Error::InvalidParameters);
    }

    // Ensure sorted and complete contributions & commitments for party IDs 0..N-1
    let mut checked = vec![false; n as usize];
    let mut contrib_seeds = vec![[0u8; 32]; n as usize];

    for (id, contrib) in contributions {
        let party = *id as usize;
        if party >= n as usize || contrib.party_id != *id {
            return Err(Error::InvalidParameters);
        }
        contrib_seeds[party] = contrib.seed;
    }

    for (id, commit) in commitments {
        let party = *id as usize;
        if party >= n as usize {
            return Err(Error::InvalidParameters);
        }
        let expected = compute_dkg_commitment(*id, &contrib_seeds[party]);
        if commit.as_slice().ct_eq(expected.as_slice()).unwrap_u8() != 1 {
            return Err(Error::InvalidShare);
        }
        checked[party] = true;
    }

    if checked.iter().any(|&c| !c) {
        return Err(Error::InvalidParameters);
    }

    // Combine all seeds: S = SHAKE-256("th-ml-dsa-dkg-seed-v1" ‖ c_0 ‖ c_1 ‖ ... ‖ c_{N-1})
    let mut h = Shake256::default();
    h.update(b"th-ml-dsa-dkg-seed-v1");
    h.update(&[n]);
    for seed in &contrib_seeds {
        h.update(seed);
    }

    let mut master_seed = [0u8; 32];
    h.finalize_xof().read(&mut master_seed);
    Ok(master_seed)
}

/// Finalize DKG: Combine seeds and execute threshold key generation.
pub fn dkg_finalize(
    master_seed: &[u8; 32],
    params: &ThresholdParams,
) -> Result<([u8; PK_BYTES], Vec<ThresholdPrivateKey>), Error> {
    keygen_from_seed(master_seed, params)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::params::get_threshold_params;
    use rand::rngs::StdRng;
    use rand::SeedableRng;

    #[test]
    fn test_dkg_end_to_end() {
        let mut rng = StdRng::seed_from_u64(12345);
        let n = 3u8;
        let t = 2u8;
        let params = get_threshold_params(t, n).unwrap();

        // Round 1: Each party generates contribution and commitment
        let mut contribs = Vec::new();
        let mut commits = Vec::new();

        for i in 0..n {
            let (c, h) = dkg_round1(i, &mut rng).unwrap();
            contribs.push((i, c));
            commits.push((i, h));
        }

        // Round 2: Verify and derive master seed
        let master_seed = dkg_round2(n, &contribs, &commits).unwrap();

        // Finalize
        let (pk, sks) = dkg_finalize(&master_seed, &params).unwrap();
        assert_eq!(sks.len(), 3);
        assert_eq!(&pk[..32], &sks[0].rho);
    }

    #[test]
    fn test_dkg_tampered_commitment_fails() {
        let mut rng = StdRng::seed_from_u64(999);
        let n = 3u8;

        let mut contribs = Vec::new();
        let mut commits = Vec::new();

        for i in 0..n {
            let (c, h) = dkg_round1(i, &mut rng).unwrap();
            contribs.push((i, c));
            commits.push((i, h));
        }

        // Tamper with party 1's commitment
        commits[1].1[0] ^= 0xFF;

        assert_eq!(dkg_round2(n, &contribs, &commits), Err(Error::InvalidShare));
    }
}
